Review list
hr-gladiolus/fec-gladiolus pull request #57
Opened 2022-12-11 23:58 UTC by cordelia-payson

I did a lot of clean up of code - comments, refactored with styled components, removed unnecessary code, refactored to include new globally state. 

Review list sort function works
Sort by filter ratings also works
Show more buttons adds two additional reviews at a time
List becomes scrollable within component

2022-12-11 23:59 UTC, cordelia-payson commented
![](https://github.trello.services/images/mini-trello-icon.png) [Reviews List Round 2](https://trello.com/c/q4AMVW2Z/75-reviews-list-round-2)

2022-12-12 15:33 UTC, Therason requested changes
Looks good! For some reason the flexbox in the `Review` component in `SingleReview.jsx` is causing the stars to not work. This is easy to fix by going into `Stars.jsx` and wrapping everything in a `<div>`. Do you think you could add that to this PR as well?

2022-12-12 15:33 UTC, Therason commented on src/components/reviews/ReviewsList.jsx
> +  overflow: scroll;
Can this be changed to `overflow-y: scroll;`? That way only a vertical scroll bar pops up.

2022-12-12 15:55 UTC, Therason approved these changes

2022-12-12 15:55 UTC, merged